CREATE DATABASE support1rtk;

CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first VARCHAR(120) NOT NULL,
    last VARCHAR(120) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    isAdmin BOOLEAN DEFAULT false,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

-- Step 1: Create the ENUM types outside the table
CREATE TYPE product_type AS ENUM ('iPhone', 'iMac', 'Macbook', 'iPad');
CREATE TYPE status_type AS ENUM ('new', 'open', 'closed');

-- Step 2: Create the table using the types
CREATE TABLE IF NOT EXISTS tickets (
    id UUID PRIMARY KEY DEFAULT uuidv7(),
    userid INTEGER REFERENCES users(id),
    product product_type,
    description TEXT NOT NULL,
    status status_type DEFAULT 'new',
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS notes (
    noteid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    userid INTEGER NOT NULL REFERENCES users(id),
    ticketid UUID NOT NULL REFERENCES tickets(id),
    text TEXT NOT NULL,
    isStaff BOOLEAN DEFAULT false,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);




